Repository osamhack2020/IoT_KookMoBan_PonJohmNaimann, pull requests merged in 2020-10, with the labels that each got.

#2 ENH : Public 상수, 함수 및 메인 루프 구현
  main.py
  phone_isFull.pickle
Labels: enhancement

#7 ENH : Key Vector 기반 이미지 Decoding 기능 구현
  main.py
  test.png
Labels: enhancement

#16 ENH : 이미지를 Base64 포맷으로 인코딩하는 함수 구현
  main.py
Labels: enhancement

#18 ENH : save.pickle에 현재 상태 저장
  main.py
  phone_isFull.pickle
  pickleInitializer.py
  save.pickle
Labels: enhancement

#22 DOC : license.md 파일 추가
  LICENSE
Labels: documentation

#23 DOC : README.md 파일 추가
  README.md
Labels: documentation

#24 ENH: 서버에 반납 기록을 전송하는 server_returnLog 함수 구현
  cam.jpeg
  main.py
  return_photo.jpeg
  temp.jpg
Labels: enhancement, iot<->server

#26 DOC : 반납기 구조 간단히 설계
  productPhoto/structure01.png
  productPhoto/structure02.png
  productPhoto/structure03.png
Labels: documentation

#28 BUG : 함수의 정의 순서를 조정하고 phone_autoCut을 사용하도록 함.
  cam.jpeg
  main.py
Labels: bug

#29 CLN : 서버 URL 변경 및 코드 정리
  cam.jpeg
  main.py
Labels: cleanup

#30 CLN : 테스트 파일을 한 폴더로 묶어 정리
  license.md
  test/temp.jpg
  test/temp.py
  test/test.png
  test/test_Validation.py
Labels: cleanup

#33 DOC : 팀 로고 제작
  productPhoto/teamLogo.psd
  productPhoto/teamLogo02.psd
  productPhoto/teamLogo03.jpg
  productPhoto/teamLogo03.psd
  productPhoto/teamLogo04.jpg
  productPhoto/teamLogo04.psd
  productPhoto/teamLogo05.jpg
  productPhoto/teamLogo05.psd
Labels: documentation

#34 ENH : 문 잠금, 잠금해제 관리 코드 작성
  LICENSE
  cam.jpeg
  main.py
  temp.jpg
  temp.py
  test.png
  test_Validation.py
Labels: enhancement

#36 CLN : 개발 환경을 윈도우PC에서 라즈베리파이로 이전, 코드 수정
  cam.jpeg
  main.py
Labels: cleanup, raspPi

#40 ENH : 지금 시간이 핸드폰 사용가능 시간인지 서버로부터 확인받는 기능 구현
  main.py
Labels: enhancement

#42 DOC : 회로도 circuit.jpg 첨부
  productPhoto/circuit.ai
  productPhoto/circuit.jpg
Labels: documentation

#43 ENH : QR코드에서 adminId를 추가로 읽고 time_isForUse에서도 활용
  cam.jpeg
  main.py
  pickleInitializer.py
  save.pickle
Labels: enhancement, iot<->server

#45 ENH : 반납기 회로 작성 및 라즈베리파이 GPIO 설정
  autocut.jpg
  cam.jpeg
  main.py
  return_photo.jpeg
  save.pickle
Labels: bug, enhancement, raspPi

#48 ENH : 압력센서 사용 가능!
  capture.jpg
  decrypted.jpg
  main.py
Labels: arduino, enhancement, raspPi

#50 ENH : 서보모터를 제어하여 문 열고 닫기
  capture.jpg
  decrypted.jpg
  main.py
Labels: enhancement, raspPi

#52 TST : 테스트용 마스터 TOTP 설정
  main.py
  test/original.png
  test/qr_decoder.py
  test/qr_gen.py
  test/result.png
Labels: test

#54 DOC : 반납기 회로도 업데이트
  cam.jpeg
  main.py
  productPhoto/circuit.ai
  productPhoto/circuit.jpg
Labels: documentation

#56 ENH : 상태표시 LED 점등
  capture.jpg
  decrypted.jpg
  main.py
Labels: enhancement, raspPi

#58 CLN : QR코드 인식, TOTP인증시 콘솔에 출력
  main.py
Labels: cleanup

#60 TST : 테스트용 마스터 QR코드 개선
  cam.jpeg
  capture.jpg
  main.py
  test/original.png
  test/qr_gen.py
  test/result.png
Labels: iot<->app, test

#62 BUG : 핸드폰 불출시 보조조명이 꺼지지 않는 버그 수정
  cam.jpeg
  capture.jpg
  main.py
Labels: enhancement, raspPi

#64 ENH : 반납기 무게센서 Calibration
  main.py
Labels: enhancement, raspPi

#66 DOC : 흰색배경 팀 로고 제작
  productPhoto/teamLogo05_inv.jpg
  productPhoto/teamLogo05_inv.psd
Labels: documentation

#68 DOC : 반납기 회로도 LED, 스위치 관련 부분 수정
  productPhoto/circuit.ai
  productPhoto/circuit.jpg
Labels: documentation, raspPi

#70 BUG : 상태표시 LED 제어 코드 정상화 및 App에서 받은 QR코드 JSON화
  cam.jpeg
  capture.jpg
  main.py
Labels: bug, iot<->app, raspPi

#73 BUG : QR코드 JSON key값 수정, TOTP 인증 관련 수정, QR코드 인식 시간 기록 시점 조정
  autocut.jpg
  cam.jpeg
  capture.jpg
  main.py
Labels: bug, iot<->app, iot<->server, raspPi

#76 DOC : 회로도에서 서보모터를 하나만 남김
  productPhoto/circuit.ai
  productPhoto/circuit.jpg
Labels: documentation

#78 DOC : 반납기 3D 모델링 및 가이드 추가
  iot_docu/circuit.ai
  iot_docu/circuit.jpg
  iot_docu/concept01.png
  iot_docu/concept02.png
  iot_docu/concept03.png
  iot_docu/hw_build_guide/01-1.ai
  iot_docu/hw_build_guide/01-1.jpg
  iot_docu/hw_build_guide/01.png
  iot_docu/hw_build_guide/02-1.ai
  iot_docu/hw_build_guide/02-1.jpg
  iot_docu/hw_build_guide/02.png
  iot_docu/hw_build_guide/03-1.ai
  iot_docu/hw_build_guide/03-1.jpg
  iot_docu/hw_build_guide/03.png
  iot_docu/hw_build_guide/04-1.ai
  iot_docu/hw_build_guide/04-1.jpg
  iot_docu/hw_build_guide/04.png
  iot_docu/hw_build_guide/05-1.ai
  iot_docu/hw_build_guide/05-1.jpg
  iot_docu/hw_build_guide/05.png
  iot_docu/hw_build_guide/06.png
  iot_docu/model/Receiver - Part 1.stl
  iot_docu/model/Receiver - Part 2.stl
  iot_docu/model/Receiver - Part 3.stl
  iot_docu/model/Receiver - Part 4.stl
  iot_docu/model/Receiver - Part 5.stl
  iot_docu/model/Receiver - Part 6.stl
  iot_docu/model/Receiver - Part 7.stl
  team_docu/teamLogo.psd
  team_docu/teamLogo02.psd
  team_docu/teamLogo03.jpg
  team_docu/teamLogo03.psd
  team_docu/teamLogo04.jpg
  team_docu/teamLogo04.psd
  team_docu/teamLogo05.jpg
  team_docu/teamLogo05.psd
  team_docu/teamLogo05_inv.jpg
  team_docu/teamLogo05_inv.psd
Labels: documentation

#79 ENH : 아두이노 전용 소스코드 업로드 및 폴더 정리
  arduino/sketch_oct17a.ino
  autocut.jpg
  cam.jpeg
  capture.jpg
  decrypted.jpg
  img/IMG_0289.jpg
  img/IMG_0290.jpg
  img/IMG_0291.jpg
  img/IMG_0292.jpg
  img/IMG_0293.jpg
  img/IMG_0295.jpg
  img/IMG_0296.jpg
  img/IMG_0297.jpg
  img/IMG_0298.jpg
  img/IMG_0299.jpg
  img/IMG_0300.jpg
  img/IMG_0301.jpg
  iot_docu/circuit.jpg
  iot_docu/hw_build_guide/01-1.jpg
  iot_docu/hw_build_guide/02-1.jpg
  iot_docu/hw_build_guide/03-1.jpg
  iot_docu/hw_build_guide/04-1.jpg
  iot_docu/hw_build_guide/05-1.jpg
  raspi/main.py
  raspi/pickleInitializer.py
  save.pickle
  team_docu/teamLogo03.jpg
  team_docu/teamLogo04.jpg
  team_docu/teamLogo05.jpg
  team_docu/teamLogo05_inv.jpg
  test/temp.jpg
Labels: documentation, enhancement

#81 CLN : 시리얼 통신 포트 관련 변수 SERIAL_PORT 추가
  raspi/main.py
Labels: cleanup

#83 DOC : 시연영상 링크 첨부
  showdown_video/시연영상 주소.txt
Labels: documentation

#84 커밋 잘못해서 이미지파일 다수 날려먹어서 복구
  iot_docu/hw_build_guide/01-1.jpg
  iot_docu/hw_build_guide/02-1.jpg
  iot_docu/hw_build_guide/03-1.jpg
  iot_docu/hw_build_guide/04-1.jpg
  iot_docu/hw_build_guide/05-1.jpg
  iot_docu/hw_build_guide/whole.gif
  team_docu/teamLogo05.png
  team_docu/teamLogo05_inv.png
Labels: bug

#86 Merge pull request #85 from osamhack2020/DOC-라이센스-BSD-3로-변경
  license.md
Labels: documentation

#88 CLN : 리포지토리 폴터, 파일 정리
  LICENSE
  arduino/sketch_oct17a.ino
  doc/iot_docu/3d_model/Receiver - Part 1.stl
  doc/iot_docu/3d_model/Receiver - Part 2.stl
  doc/iot_docu/3d_model/Receiver - Part 3.stl
  doc/iot_docu/3d_model/Receiver - Part 4.stl
  doc/iot_docu/3d_model/Receiver - Part 5.stl
  doc/iot_docu/3d_model/Receiver - Part 6.stl
  doc/iot_docu/3d_model/Receiver - Part 7.stl
  doc/iot_docu/circuit/circuit.ai
  doc/iot_docu/circuit/circuit.jpg
  doc/iot_docu/concept_photo/concept01.png
  doc/iot_docu/concept_photo/concept02.png
  doc/iot_docu/concept_photo/concept03.png
  doc/iot_docu/hw_build_guide/01-1.ai
  doc/iot_docu/hw_build_guide/01-1.jpg
  doc/iot_docu/hw_build_guide/01.png
  doc/iot_docu/hw_build_guide/02-1.ai
  doc/iot_docu/hw_build_guide/02-1.jpg
  doc/iot_docu/hw_build_guide/02.png
  doc/iot_docu/hw_build_guide/03-1.ai
  doc/iot_docu/hw_build_guide/03-1.jpg
  doc/iot_docu/hw_build_guide/03.png
  doc/iot_docu/hw_build_guide/04-1.ai
  doc/iot_docu/hw_build_guide/04-1.jpg
  doc/iot_docu/hw_build_guide/04.png
  doc/iot_docu/hw_build_guide/05-1.ai
  doc/iot_docu/hw_build_guide/05-1.jpg
  doc/iot_docu/hw_build_guide/05.png
  doc/iot_docu/hw_build_guide/06.png
  doc/iot_docu/hw_build_guide/whole.gif
  doc/showdown_video/youtube_link.txt
  doc/team_logo/teamLogo05.png
  doc/team_logo/teamLogo05.psd
  doc/team_logo/teamLogo05_inv.png
  doc/team_logo/teamLogo05_inv.psd
  src/advanced/qr_decoder.py
  src/advanced/qr_gen.py
  src/arduino/weight_reader.ino
  src/raspi/main.py
  src/raspi/pickleInitializer.py
  team_docu/teamLogo.psd
  team_docu/teamLogo02.psd
  team_docu/teamLogo03.psd
  team_docu/teamLogo04.psd
  test/original.png
  test/result.png
  test/temp.py
  test/test.png
  test/test_Validation.py
Labels: cleanup

#92 CLN : LICENSE -> LICENSE.md
  LICENSE.md
Labels: cleanup

#94 Update README.md
  README.md
Labels: cleanup
